from minio/mc:RELEASE.2019-08-07T23-14-43Z

# Set one or more individual labels
LABEL dsb.minio-mc.version="2019-08-07T23-14-43Z"
LABEL vendor="DSB Minio mc"
LABEL dsb.minio-mc.release-date="2019-08-07T23-14-43Z"
LABEL dsb.minio-mc.version.is-production=""

COPY /bin/entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh