from minio/minio:RELEASE.2019-07-24T02-02-23Z

# Set one or more individual labels
LABEL dsb.minio.version="2019-07-10T00-34-56Z"
LABEL vendor="DSB Minio"
LABEL dsb.minio.release-date="2019-07-10T00-34-56Z"
LABEL dsb.minio.version.is-production=""
# Environment labels

