# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: dsb-postgres:v1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "castello"