#
# example Dockerfile for https://docs.docker.com/engine/examples/postgresql_service/
#

FROM postgres:11.4

RUN echo "host all all 0.0.0.0/0  md5" >> /var/lib/postgresql/data/pg_hba.conf

# Set one or more individual labels
LABEL dsb.mongo.version="11.4.v1"
LABEL vendor="DSB Postgres"
LABEL dsb.mongo.release-date="July 15 2019"
LABEL dsb.mongo.version.is-production=""

# Environment labels
ENV POSTGRES_PASSWORD=unkown
ENV POSTGRES_USER=unkown
ENV POSTGRES_DB=unkown