# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: dbranizor/dsb:postgres-11.4-v2
    restart: always
    ports:
      - 5433:5432
    volumes: 
      - ~/storage/kc:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "castello"
