version: '3.1'

services:
  mongo:
    image: dsb-mongo:v1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: eich
      MONGO_USER: ${MONGO_USER}
      MONGO_INITDB_DATABASE: eich
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27018:27017