version: '3.3'

services:
  mongo:
    image: dsb-mongo:latest
    restart: always
    volumes:
      - dbvolume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD:-p@ssw0rd}"
      MONGO_DATABASE: "${MONGO_DB:-user}"
      MONGO_USER: "${MONGO_USER:-bud}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DB:-init}"
      MONGO_PASSWORD: "${MONGO_PASSWORD:-p@ssw0rd}"
    ports:
      - "${MONGO_HOST_PORT:-27017}:${MONGO_PORT:-27017}"
volumes:
  dbvolume:
